kiwoom:
  base_url:
    paper: https://mockapi.kiwoom.com
    live: https://api.kiwoom.com
  endpoints:
    authenticate: /oauth2/token
    candles: /uapi/domestic-stock/v1/quotations/inquire-time-itemchartprice
    supply: /uapi/domestic-stock/v1/quotations/inquire-investors
    balance: /uapi/domestic-stock/v1/trading/inquire-balance
    account_overview: /api/dostk/acnt
    order: /uapi/domestic-stock/v1/trading/order-cash
    logout: /oauth2/revoke
    market_condition: /api/dostk/mrkcond
  default_headers:
    Content-Type: application/json;charset=UTF-8
  account_overview_api_id: kt00004
  market_condition_api_id: ka10005
  timeframes:
    - tick
    - 1m
    - 5m
    - 15m
    - 1h
    - 6h
market_indices:
  - kospi
  - kosdaq
data_retention_days: 365
